# Generated by Django 2.1 on 2020-12-23 22:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Title')),
                ('streaming', models.CharField(max_length=100, verbose_name='Straming')),
                ('server', models.CharField(max_length=100, verbose_name='Server')),
                ('trailer', models.CharField(max_length=100, verbose_name='Trailer')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('description', models.CharField(max_length=30, verbose_name='Description')),
                ('category', models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('cartoon', 'Cartoon')], max_length=50, verbose_name='Category')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='Poster')),
                ('date_added', models.DateTimeField(default=datetime.datetime.now, verbose_name='Created At')),
                ('manager', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
